---
- hosts: all
  remote_user: ec2-user

  tasks:
  - name: install java 8
    yum:
     name: java-1.8.0
     state: latest
    become: true
    become_method: sudo

  - name: remove java 7
    yum:
     name: java-1.7.0-openjdk
     state: removed
    become: true
    become_method: sudo