---
- hosts: all
  remote_user: ec2-user

  tasks:
  - name: Copy Elasticsearch repo
    copy:
     src: elasticsearch.repo
     dest: /etc/yum.repos.d/elasticsearch.repo
     owner: ec2-user
     mode: 0644
    become: true

  - name: Install Elasticsearch
    yum: 
     name: elasticsearch
     state: present
    become: true

  - name: Update the config file to allow outside access
    lineinfile:
     destfile: /etc/elasticsearch/elasticsearch.yml
     regexp: 'network.host:'
     line: 'network.host: 0.0.0.0'
    become: true

  - name: Update the port in config file 
    lineinfile:
     destfile: /etc/elasticsearch/elasticsearch.yml
     regexp: 'http.port:'
     line: 'http.port: 9200'
    become: true

  - name: Configure heap min size
    lineinfile: 
     destfile: /etc/elasticsearch/jvm.options
     regexp: '-Xms2g'
     line: '-Xms200m'
    become: true

  - name: Configure heap max size
    lineinfile: 
     destfile: /etc/elasticsearch/jvm.options
     regexp: '-Xmx2g'
     line: '-Xmx200m'
    become: true

  - name: Start Elasticsearch
    service:
     name: elasticsearch
     state: started
    become: true