node {
	stage('Prepare Ansible Hosts') {
		checkout scm
		sh "echo ${elkTarget} >> ./ansible/ansible_hosts"
	}

	stage('Install Java 8') {
		sh "/usr/local/bin/ansible-playbook -i ansible/ansible_hosts ansible/roles/java8/tasks/main.yml"
	}
}