node {
	stage('Prepare Ansible Hosts') {
		checkout scm
		sh "echo ${elkTarget} >> ./ansible/ansible_hosts"
	}

	stage('Install Java 8') {
		withEnv(["PATH=$PATH:/usr/local/bin"]) {
			ansiblePlaybook(
				playbook: './ansible/roles/java8/tasks/main.yml',
				inventory: './ansible/ansible_hosts',
				credentialsId: 'id_rsa'
			)
		}
	}
}