---
- hosts: all
  remote_user: ec2-user

  tasks: 
  - name: Copy logstash repo 
    copy:
     src: logstash.repo
     dest: /etc/yum.repos.d/logstash.repo
     owner: jenkins
     mode: 0644
    become: true

  - name: Install logstash
    yum: 
     name: logstash
     state: present
    become: true